name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker build -t 7px7hctzvznazc/c-app:$GITHUB_SHA .
          docker push 7px7hctzvznazc/c-app:$GITHUB_SHA
        
